# Generated by Django 5.1.7 on 2025-03-24 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmes',
            old_name='filmmax_digitse',
            new_name='filme',
        ),
    ]
