# Generated by Django 5.1.7 on 2025-03-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_rename_filmmax_digitse_filmes_filme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='preco',
            field=models.FloatField(max_length=8, verbose_name='Preço'),
        ),
    ]
